# Generated by Django 3.2.8 on 2021-10-31 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='apartment',
            field=models.CharField(choices=[('guest', 'guest'), ('a1', 'A1'), ('a2', 'A2'), ('a3', 'A3'), ('b1', 'B1'), ('b2', 'B2'), ('b3', 'B3'), ('c2', 'C2'), ('c3', 'C3'), ('c4', 'C4'), ('c5', 'rooftop house')], max_length=40),
        ),
    ]
