# Generated by Django 3.2.8 on 2021-10-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_type_product'),
        ('users', '0009_auto_20211017_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cart',
            field=models.ManyToManyField(blank=True, to='products.Product'),
        ),
    ]
