# Generated by Django 3.2.8 on 2021-10-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_type_product'),
        ('users', '0012_alter_user_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='appartment',
            field=models.CharField(blank=True, choices=[('a1', 'A1'), ('a2', 'A2'), ('a3', 'A3'), ('b1', 'B1'), ('b2', 'B2'), ('b3', 'B3'), ('c2', 'C2'), ('c3', 'C3'), ('c4', 'C4'), ('c5', 'rooftop house')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cart',
            field=models.ManyToManyField(blank=True, to='products.Product'),
        ),
    ]
