# Generated by Django 3.2.8 on 2021-10-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20211017_1712'),
        ('users', '0016_alter_user_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cart',
            field=models.ManyToManyField(blank=True, to='products.Product'),
        ),
    ]
