# Generated by Django 3.2.8 on 2021-10-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_type_product'),
        ('users', '0021_alter_user_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cart',
            field=models.ManyToManyField(blank=True, to='products.Product'),
        ),
    ]
