# Generated by Django 3.2.8 on 2021-10-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='place',
            field=models.CharField(choices=[('guesthouse', 'guest house'), ('hairsalon', 'hairsalon'), ('facility', 'facility'), ('general', 'general')], default='general', max_length=20),
        ),
    ]
