# Generated by Django 3.2.8 on 2021-10-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_type_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='type',
            name='product',
            field=models.ManyToManyField(related_name='type', to='products.Product'),
        ),
    ]
