# Generated by Django 3.2.8 on 2021-10-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20211017_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='product',
            field=models.ManyToManyField(related_name='type', to='products.Product'),
        ),
    ]
