# Generated by Django 3.2.8 on 2021-10-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_type_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='product_photos'),
        ),
        migrations.AlterField(
            model_name='type',
            name='product',
            field=models.ManyToManyField(related_name='type', to='products.Product'),
        ),
    ]
